import os

# mapbox
MAP_API = os.environ.get('MAP_API')

##################  VARIABLES  ##################



##################  CONSTANTS  #####################
STOPWORDS = [('food', 407452),
 ('good', 248393),
 ('service', 217139),
 ('great', 138171),
 ('staff', 117568),
 ('nice', 110294),
 ('place', 108332),
 ('restaurant', 86786),
 ('dish', 84913),
 ('time', 78530),
 ('delicious', 78503),
 ('friendly', 73322),
 ('really', 72500),
 ('u', 66628),
 ('taste', 65326),
 ('also', 61263),
 ('experience', 61009),
 ('like', 60406),
 ('one', 57355),
 ('back', 56299)]


# main_category to remove from restaurant_name.csv
CATS_TO_REMOVE = ['Manufacturer', 'Maternity store', 'Mining company', 'Barber shop', 'Preschool', 'Bazar',
"Women's clothing store", 'Dessert shop', 'Art gallery', 'Branding agency', 'Medical equipment supplier',
'Waxing hair removal service', 'Day care center', 'Computer support and services', 'E-commerce service',
'Grocery store', 'Lawyer', 'Educational institution', 'Importer', 'Coffee shop', 'Public parking space',
'Food and drink', 'Medical Center', 'Day spa', 'Kitchen supply store', 'Karaoke bar', 'Delivery Chinese',
'Chinese language school', 'Credit counseling service', 'Artist', 'Goldsmith', 'MRT/LRT Station',
'Youth Centre', 'Education center', 'Walk-in clinic', 'Caterer', 'Tourist attraction', 'Design agency',
'Playground', 'Hiking area', 'Personal trainer', 'Muay Thai boxing gym', 'Non-profit organization',
'Optician', 'Transport interchange', 'Wellness center', 'Indoor playground', 'Japanese sweets restaurant',
'Plastic products supplier', 'Fish store', 'Dog cafe', 'Candle store', 'Shopping mall',
'Health and beauty shop', 'Clothing store', 'Association / Organization', 'Medical clinic',
'Food manufacturer', 'Pest control service', 'Souvenir store', 'Delivery Restaurant',
'Tattoo and piercing shop', 'Law firm', 'Contractor', 'Gold dealer', 'Cement manufacturer', 'Lounge',
'Oral surgeon', 'Property management company', 'Construction company', 'Website designer', 'Tattoo shop',
'Furniture store', 'Shop', 'Software company', 'Chinese bakery', 'Tea and coffee shop',
'Food manufacturing supply', 'Photographer', 'Print shop', 'Chinese Takeaway', 'Coffee roasters',
'Finance broker', 'Commercial cleaning service', 'Employment agency', 'Sports bar', 'Accountant',
'Organic food store', 'Industrial Real Estate Agency', 'Book store', 'Commercial real estate inspector',
'Self service restaurant', 'HDB Flats', 'Internet marketing service', 'Farm shop', 'Event planner', 'ATM',
'Government office', 'Açaí shop', 'Memorial park', 'Educational testing service', 'Photography',
'Computer security service', 'Food court', 'Financial institution', 'Homewares Store',
'Wedding photographer', 'Real estate consultant', 'Importer and Exporter', 'Art center', 'Media company',
'Pub', 'Hostel', 'Charity', 'Event venue', 'Computer store', 'Dance store', 'Fruit wholesaler',
'Chocolate cafe', 'Serviced accommodation', 'Social club', 'Designer Clothing Shop', 'Pet Shop',
'Police station', 'Hardware store', 'Pizza takeaway', 'Real estate developer', 'Counselor',
'Japanese confectionery shop', 'Curtain and upholstery cleaning service', 'Wine cellar', 'Tailor',
'Department store', 'Engineer', 'Bus Interchange', 'Interior designer', 'Housing development',
'Otolaryngologist', 'Shipping and mailing service', 'Food producer', 'General practitioner', 'Cake shop',
'Baby store', 'Financial planner', 'Gourmet grocery store', 'Performing arts theater', 'Massage spa',
'Occupational therapist', 'School', 'Bus depot', 'Language school', 'Mattress store', 'Shipping service',
'Live music venue', 'Jewelry store', 'Art studio', 'Catholic church', 'Sushi takeaway', 'Diving center',
'Sandwich shop', 'Indian grocery store', 'Chocolate shop', 'Wholesaler', 'Consultant',
'Local government office', 'Bus stop', 'Club', 'Tiffin center', 'Car detailing service',
'Indoor golf course', 'Ballet school', 'Jeweler', 'Artistic handicrafts', 'Art museum',
'Movie rental store', 'Condominium complex', 'Chinese tea house', 'Dental clinic', 'Wholesale food store',
'Chocolate artisan', 'Used clothing store', 'Corporate gift supplier', 'Seafood wholesaler',
'Legal services', 'Butcher shop', 'Employment center', 'Coffee store', 'Frozen food store',
'Hawker center', 'Business management consultant', 'After school program', 'Steamed bun shop', 'Deli',
'Ice cream shop', 'Plant nursery', 'Advertising agency', 'Bed & breakfast', 'Soup kitchen',
'Wedding venue', 'Health spa', 'Holding company', 'Catering food and drink supplier',
'Music management and promotion', 'Apartment building', 'Fruit and vegetable wholesaler',
'Real estate agent', 'Business to business service', 'Boutique', 'Wedding planner',
'Alcoholic beverage wholesaler', 'Cosmetics and perfumes supplier', 'Luggage store', 'Dance school',
'Lodging', 'Kitchen', 'Martial arts club', 'Florist', 'Lottery retailer', 'Toy store', 'Flower delivery',
'Music producer', 'Trading company', 'Beauty product supplier', 'Insurance company', 'Cinema',
'Optometrist', 'Heritage building', 'Bank', 'Tutoring service', 'Parking lot', 'Hairdresser',
'Makerspace', 'Publisher', 'Tea house', 'Butcher shop deli', 'Employment consultant', 'Stationery store',
'Coworking space', 'Marketing consultant', 'Performing arts group', 'Convenience store',
'Community garden', 'Business center', 'House cleaning service', 'Scenic spot', 'Health food store',
'Takeaways', 'Garden', 'Learning center', 'Monument maker', 'Wellness program', 'Bubble tea store',
'Bakery', 'Recording studio', 'Motorcycle rental agency', 'Garden center', 'Electronics manufacturer',
'Religious organization', 'Real estate agency', 'Cultural association', 'Shoe Shop',
'Family service center', 'Moving and storage service', 'Camping Ground', 'Chartered accountant',
'Financial consultant', 'Fashion accessories store', 'Confectionery store', 'Supermarket', 'Industry',
'Non-governmental organization', 'Rice restaurant', 'Religious destination', 'Haute French restaurant',
'Food products supplier', 'Memorial estate', 'Car dealer', 'Taoist temple', 'Japanese grocery store',
'National forest', 'Bridal shop', 'Event management company', 'Unknown', 'Pastry shop', 'Antique store',
'Nail salon', 'Museum', 'Light rail station', 'Beauty salon', 'Coaching center', 'Fast food restaurant',
'Video production service', 'Apartment complex', 'Tea store', 'Warehouse', 'Freight forwarding service',
'Photography service', 'Gym and Fitness Centre', 'Ice supplier', 'Coffee stand', 'Corporate office',
'Hawker Stall', 'Air conditioning store', 'Italian grocery store', 'Recruiter', 'Transportation service',
'Camera store', 'Laboratory equipment supplier', 'Travel agency', 'Music school', 'Auditor',
'Anglican church', 'Athletic field', 'Pharmacy', 'Shoe repair shop', 'Kiosk', 'Yoga studio',
'Restaurant supply store', 'Hair salon', 'Marketing agency', 'Swimming school', 'Wedding store',
'Hematologist', 'Gemologist', 'Property Investment', 'Coffee wholesaler', 'Wholesale bakery',
"Children's clothing store", 'Patisserie', 'Hotel', 'Lighting store', 'Gift shop', 'Bicycle club',
'Industrial equipment supplier', 'Information services', 'Salad shop', 'Car wash', 'Market',
'Electroplating Service', 'Sundae restaurant', 'Insurance', 'Acupuncture clinic', 'Park'
]

PLACE_ID_TO_DROP = [
    'ChIJh5Y59BQT2jERURiZLDQx4nw',
    'ChIJZ1fwClsb2jERObWFCMIH9vs',
    'ChIJPQnKqsAZ2jERwwkvvSyGZFg',
    'ChIJq6p6aIEa2jERLuWrj4ANh8E',
    'ChIJN33CKWIQ2jERMg_rME_Bay0',
    'ChIJd4WNfZ4Z2jERg12q-wfG2as',
    'ChIJ71CS0r0Z2jER8-smeu34jjY',
    'ChIJL4PDN6kZ2jERThaNWhOn098',
    'ChIJXd0PKYEX2jERYrueyc06grw',
    'ChIJ6Ykv9HEQ2jERsEXyHWa-R9Q',
    'ChIJVVUVem4Q2jERWIpWwfLUvOM',
    'ChIJ_aBCmBQZ2jERq5LkmNBX4ow',
    'ChIJAWnNhWgX2jERdqeKX3ll9_A',
    'ChIJ56hvaFoQ2jER6UYrXGNDQGc',
    'ChIJYzNuVSQX2jERq0kUBaonauY',
    'ChIJ-5iwVQsZ2jERDYQr5iyYDbI',
    'ChIJR-uLmRIZ2jERB3x-oYjX6-8',
    'ChIJu63tBLEZ2jER4BWy9m52vtI',
    'ChIJl0y967gZ2jER61Sh6YJd_Yg',
    'ChIJE3D9Nysa2jERVnXUtHpekrE',
    'ChIJzSendw0Z2jERTiGG5HBCUdI',
    'ChIJZVV0h2wZ2jER62ZOIpoV2P8',
    'ChIJ__8PEIka2jERVGgDfS-2K10',
    'ChIJS_BEA7oZ2jER2GK5z-e8qoQ',
    'ChIJAQAASX0Z2jERVYuMyQfqAQA',
    'ChIJx9FYtnUZ2jER922k1B_LAzk',
    'ChIJKf5YyxIZ2jERILku5keIlJg',
    'ChIJUcN6xW0Y2jERC2-GL6l2z7E',
    'ChIJaW3kmZYV2jER-uORG7aXKyU',
    'ChIJsQVGb_oX2jERvDAu0xkL6zA',
    'ChIJrTFZ9rcZ2jER2xBp6b8aOHA',
    'ChIJ7-afsQwZ2jER2f0eExqzue0',
    'ChIJezI5f7gX2jERa0J7b7iGbuk',
    'ChIJnxVgCG0Z2jER3-HA5RXp6Qw',
    'ChIJV_7XqfYX2jERCCwSnrmQ3Nc',
    'ChIJq6q278sb2jERWGHFlfEVmfY',
    'ChIJ8RANNaEZ2jERgf3U0gAdTgE',
    'ChIJZWEkZgsZ2jER0WnuE6HDzoE',
    'ChIJEUEayA4Z2jERNH_S8TPONm4',
    'ChIJ3eVZlQ4Z2jERX34jdgqlI28',
    'ChIJ-TsVF6kb2jER1_NGlLmqZmk',
    'ChIJvSxGnpcZ2jERJCmBscFz3Dw',
    'ChIJ3Tcl0IwZ2jER7_dBq_HSCbA',
    'ChIJKdihA68Z2jER07IZ_I3hEVI',
    'ChIJicht9G0Y2jER1DYdsrIIJw8',
    'ChIJ__8_wYwZ2jERtCSn02_fhzY',
    'ChIJo5fvvQwZ2jERz_JUcD4fzkg',
    'ChIJ__-vj-8Z2jERhye3e6pRpaM',
    'ChIJfaAGgMgZ2jERwVcV4SINwwg',
    'ChIJYd_hd0kZ2jERN9FWlI4xJto',
    'ChIJ9eNkeP4b2jERmH8pwHymE6M',
    'ChIJk0XVZ9YZ2jERuGEbtTayWNA',
    'ChIJ5z4oO2MZ2jERB3lOJkfCyhw',
    'ChIJa58Ty48T2jER7w4mWnrfWEM'
]

NAMES_TO_DROP = ['Leila katheera', 'Dempsey Hill', 'Encik Tan', 'Tian Huat Rice Stall',
'Mr Teh Tarik Eating House', 'Shake Shack (Suntec)', 'Shake Shack 89 Neil Road', 'Shake Shack Great World'
]

RESTAURANT_RECATEGORIZATION = {
    'Waroeng Anak Indo': 'Indonesian',
    'Samrang SG': 'Korean',
    'Restaurant Poise': 'French',
    'Revolver': 'Indian',
    'Rod Dee Thai Cafe': 'Thai',
    'Dickson Nasi Lemak': 'Malaysian',
    'SKAI Restaurant': 'Western',
    'SUSHISAMBA Singapore': 'Fusion',
    'Saap Saap Thai': 'Thai',
    'Salt & Pepper Pte Ltd': 'Western',
    'San Laksa Steamboat Pte Ltd': 'Local',
    'San Shu Gong Private Dining 三叔公私房菜': 'Chinese',
    'Sanook Kitchen - West Gate': 'Thai',
    'Sanook Kitchen - City Square': 'Thai',
    'Sakari Sushi': 'Japanese',
    'Warung Selera Masakan Kampung': 'Malaysian',
    'Selera Utama Kampung Plentong Baru (Sup Power)': 'Malaysian',
    'Selera Kampung': 'Malaysian',
    'Restoran Selera Sambal': 'Malaysian',
    'Medan Selera Kampung Tengah Gedok': 'Malaysian',
    'Restoran Selera Kampung': 'Malaysian',
    'Restoran Selera Kampung (FAM MAJU)': 'Malaysian',
    'SHUNFENG 顺风川渝私房菜': 'Chinese',
    '蜀都丰 SO DO FUN @ MIDTOWN HOUSE': 'Chinese',
    'Hibiscus Tree (芙蓉树下) Millenia Walk': 'Chinese',
    '天府李川菜 DAINTY SICHUAN': 'Chinese',
    '辣不辣 Labula BBQ Sichuan Restaurant @ Hougang Village': 'Chinese',
    'Fukurou Kitchen': 'Japanese',
    'Sin Manbok Korean Restaurant 신만복': 'Korean',
    'Sinpopo Brand Restaurant @ TANGS': 'Local',
    'Siri House Dempsey': 'Asian',
    'Sky View Pavilion': 'Chinese',
    'Soi 19 Thai Wanton Mee Telok Ayer': 'Thai',
    'Soon Huat (JB) Bak Kut Teh': 'Local',
    'Steamboat Charcoal Claypot Prawn @Toa Payoh': 'Local',
    'Crab Wang Imperial Dining': 'Chinese',
    'Sum Dim Sum (Bedok)': 'Chinese',
    'Sum Dim Sum (Punggol)': 'Chinese',
    'Summer Hill': 'Western',
    'Tamba': 'Indian',
    'Riverwalk Tandoor': 'Indian',
    'Ashoka Tandoor Family Restaurant': 'Indian',
    'Tandoor Lounge | Indian Restaurant Punggol': 'Indian',
    'Tangled': 'Italian',
    'Tapas,24 Singapore': 'Spanish',
    'Sap Ubon Thai Cuisine (Homebased)': 'Thai',
    'Thaitanium': 'Thai',
    'The Banana Leaf Apolo': 'Indian',
    'The Curry Wok (TCW)': 'Indian',
    'The French Ladle': 'French',
    'The Guild': 'Western',
    'The Kongsee': 'Fusion',
    'The NCO Club': 'Fusion',
    'The Palace Korean Restaurant': 'Korean',
    'Simply Peranakan Cuisine': 'Peranakan',
    'The Tavern Restaurant': 'Western',
    'Thevar': 'Indian',
    'Three Blind Pigs': 'Western',
    'Tian Yu Tian 天与天 Fish Head Steamboat': 'Chinese',
    'Tian Tian You Yu 天天友魚': 'Chinese',
    'Tian Wai Tian Fish Head Steamboat(天外天鱼头炉）Veerasamy Road': 'Chinese',
    'Tiffin Room': 'Indian',
    "Tilly's by Butcher Boy": 'Western',
    'Tok Panjang@Bt. Timah': 'Peranakan',
    'Toma By The River': 'Western',
    'Town Restaurant': 'Western',
    'Istanbul Corner SG': 'Turkish',
    'Eden Restaurant': 'Asian',
    'The Mask Restaurant and Bar': 'Indian',
    'UNCLE & AUNTY FAMILY RESTAURANT': 'Family',
    'Unatoto Guoco Tower': 'Japanese',
    'VENUE By Sebastian': 'European',
    'The Social Kitchen': 'Family',
    "Oscar's": 'Western',
    'The Orchard Cafe': 'Western',
    'Sampoorna Swadesi Vegetarian Restaurant': 'Indian',
    'WINESTONE': 'Western',
    'WAKUDA': 'Japanese',
    'White Rose Cafe': 'Western',
    'Willow': 'Fusion',
    'Yang Guo Fu Mala Tang 杨国福麻辣烫 @ Northpoint City': 'Chinese',
    'YinJi Singapore': 'Chinese',
    'YUAN 原': 'Chinese',
    'Ru Yi Yuan Vegetarian': 'Vegetarian',
    'Ting Yuan Hotpot Buffet': 'Chinese',
    'Yue Bai': 'Chinese',
    'Ya Ge - 雅阁 (Orchid Hotel SG)': 'Chinese',
    'Yì By Jereme Leung': 'Chinese',
    'Zén': 'European',
    'nakey': 'Western',
    'Sibarita bar & resto': 'Spanish',
    'Sibarita Restaurante': 'Spanish',
    'Sibarita': 'Spanish',
    'Sibarita Habana': 'Spanish',
    'tiram': 'Seafood',
    'The Fullerton Pavillion': 'Fusion',
    'True Cost': 'Mediterranean',
    '极鲜 Ji Xian Seafood & Hong Kong Dim Sum Express': 'Chinese',
    '老四川豆花庄': 'Chinese',
    '麻辣诱惑 Spice Spirits Singapore': 'Chinese',
    'Huda Restaurant SG 胡大饭店': 'Chinese',
    'Huevos @ River Valley': 'Mexican',
    'Humpback': 'Western',
    'ITOKO JAPANESE RESTAURANT': 'Japanese',
    'IVINS @ Thomson Plaza': 'Peranakan',
    'Adipoli Curry Pot': 'Indian',
    'Indian Tandoor Restaurant': 'Indian',
    'Indo Rasa Singapore': 'Indonesian',
    'IndoChili': 'Indonesian',
    'Ingleside': 'Western',
    'Inle Myanmar Restaurant': 'Burmese',
    'JAAN By Kirk Westaway': 'Thai',
    'Jiaxing Supreme Food House': 'Chinese',
    'Jinjo': 'Japanese',
    'La Brasserie': 'Western',
    'Leno Cakes & Deli': 'Western',
    'Lepak at Sultan': 'Asian',
    'Lolla': 'Mediterranean',
    'Lynnette\'s Kitchen (Private Dining)': 'Southeast Asian',
    'Marguerite': 'Western',
    'Meta Restaurant': 'Fusion',
    'Naga House': 'Fusion',
    'Olivia Restaurant & Lounge': 'Mediterranean',
    'Indobowl, Singapore @ Sultan Gate': 'Indonesian restaurant',
    "D'Penyetz Jem": 'Indonesian restaurant',
    'Isshin Machi Greenwood': 'Japanese restaurant',
    'Jang San Korean Restaurant 장산왕족발': 'Korean restaurant',
    'Jia Xiang Sarawak Kuching Kolo Mee': 'Malaysian restaurant',
    'Jia Xiang Sarawak Kuching Kolo Mee - Marina Square': 'Malaysian restaurant',
    'Jia Xiang Sarawak Kuching Kolo Mee - Alexandra': 'Malaysian restaurant',
    'Jiak Modern Tzechar @ Hillv2': 'Chinese restaurant',
    'Joséphine - French Cuisine & Wine Bar': 'French restaurant',
    'Kap Kun Kap Thai & Seafood': 'Thai restaurant',
    'Kazan Japanese Cuisine': 'Japanese restaurant',
    'Kim Poh FishHead Steamboat': 'Chinese restaurant',
    'fennel by komala vilas': 'Indian restaurant',
    'Korat Thai Cafe': 'Thai restaurant',
    "LET'S KINN THAI": 'Thai restaurant',
    "la table d'Emma": 'French restaurant',
    'Lao You Ji Fishhead Steamboat Seafood Restaurant': 'Chinese restaurant',
    'Lazy Lizard - Flora Vista': 'Western restaurant',
    'Le Petit Chef - Espoir Singapore': 'French restaurant',
    'Lẩu Dê 3 Cô': 'Vietnamese restaurant',
    '这边来 Zhe bian lai': 'Chinese restaurant',
    'RED DOT MALA HOTPOT 小红点麻辣香锅': 'Chinese restaurant',
    'Ri Ri Sheng Mala Hotpot': 'Chinese restaurant',
    'Xing Le Mala Hotpot': 'Chinese restaurant',
    'Madame Fan': 'Chinese restaurant',
    'Makan Japanese restaurant': 'Japanese restaurant',
    'MCC MAKAN PLACE': 'Halal restaurant',
    'Makan@Jen': 'Halal restaurant',
    'Miyu': 'Japanese restaurant',
    'TAP @ 9 Penang': 'Western restaurant',
    'Wild Coco (Hamilton Road)': 'Fusion restaurant',
    'Seroja': 'Fusion restaurant',
    'Mamacitas': 'Mexican restaurant',
    'Man Man Japanese Unagi (Clarke Quay)': 'Japanese restaurant',
    'Man Man Japanese Unagi (Duo Galleria)': 'Japanese restaurant',
    'True Veggie': 'Vegetarian restaurant',
    'NAEUM Restaurant': 'Korean restaurant',
    'Nan Hua Chang (Traditional) Fish Head Steamboat': 'Chinese restaurant',
    'Nicolas Le Restaurant': 'French restaurant',
    'Nyonyas & Gentlemen Restaurant': 'Peranakan restaurant',
    'Ocean Curry Fish Head': 'Chinese restaurant',
    'ODETTE': 'French restaurant',
    'Restaurant Odette': 'French restaurant',
    'Odette': 'French restaurant',
    'Buffet Odette': 'French restaurant',
    "Old Bibik's Peranakan Kitchen": 'Peranakan restaurant',
    'Paofan Paradise 泡饭天 - T.K Kitchen Restaurant': 'Chinese restaurant',
    'Papa Ayam 313@somerset': 'Indonesian restaurant',
    'Parkway Mini Steamboat': 'Chinese restaurant',
    'Park Bäckerei': 'German restaurant',
    "Lim's Penang Prawn Noodle and Fried Kway Teow": 'Malaysian restaurant',
    'Milligram': 'Café',
    'Podi & Poriyal': 'Vegetarian restaurant',
    'Putra Minang Restaurant Bencoolen': 'Indonesian restaurant',
    'Ăn Là Ghiền -Buffet 5': 'Vietnamese restaurant',
    'Qi - House of Sichuan': 'Chinese restaurant',
    'Qi Xiang Hotpot': 'Chinese restaurant',
    'Rainbow Rice House': 'Chinese restaurant',
    '123 ZÔ - Ẩm Thực Việt': 'Vietnamese restaurant',
    '27 Mezze Bar and Grill': 'Mediterranean restaurant',
    '57° Mala Xiang Guo @Ang Mo Kio': 'Chinese restaurant',
    '57° Mala Xiang Guo @Shaw Plaza': 'Chinese restaurant',
    '87 Club Street': 'Western restaurant',
    '88 Hong Kong Roast Meat Specialist': 'Chinese restaurant',
    'ASIAN MARKET CAFE': 'Asian restaurant',
    'Absurdities Singapore': 'Fusion restaurant',
    'Abundance: Taiwanese Restaurant & Craft Beer Bar (Redhill)': 'Taiwanese restaurant',
    "Ajumma's Northpoint": 'Korean restaurant',
    "Ajumma's Westgate": 'Korean restaurant',
    'Alegria Singapore': 'Latin American restaurant',
    'Alice Boulangerie & Restaurant': 'French restaurant',
    'Restoran Al Alif, Bandar Seri Alam': 'Indian restaurant',
    'Anglo Indian Cafe & Bar': 'Indian restaurant',
    'Apéro': 'French restaurant',
    'Arab Street Turkish & Western Restaurant': 'Turkish restaurant',
    'Hup Lee Cafeteria (Arcade Fish Soup)': 'Chinese restaurant',
    'Ayam Penyet President Express - Midtown Hougang': 'Indonesian restaurant',
    'BACARO Italian Restaurant and Wine Bar': 'Italian restaurant',
    'Bacos': 'Western restaurant',
    'Badaro Korean Seafood': 'Korean restaurant',
    'Bangkok Thai Muslim': 'Thai restaurant',
    'Bearded Bella': 'Café',
    'Beast Duxton': 'American restaurant',
    'Bee Keong Restaurant': 'Chinese restaurant',
    'Bella pizzeria': 'Italian restaurant',
    'Berlin65': 'German restaurant',
    'Bugis BBQ and Hotpot': 'Chinese restaurant',
    'Bugis Fish Head Steamboat': 'Chinese restaurant',
    'Buko Nero': 'Italian restaurant',
    'Thien Long Vietnamese Food': 'Vietnamese restaurant',
    'Star Pho Le Beef Noodle Soup ( Subsidiary of Banh Mi Thit by Star Baguette )': 'Vietnamese restaurant',
    "Làng Nướng 1980's - Authentic Vietnamese home-cooked Cuisine": 'Vietnamese restaurant',
    'Ăn Là Ghiền-Cơm Niêu': 'Vietnamese restaurant',
    'COL': 'Fusion restaurant',
    'COLLECTIVE': 'Fusion restaurant',
    'Well Collective': 'Fusion restaurant',
    'Cafe de Muse - The Restaurant': 'Café',
    'Caffe Fernet': 'Italian restaurant',
    'Cendra Tapas Bar and Grill': 'Spanish restaurant',
    "Charlie's Restaurant & Bar (Boat Quay)": 'Western restaurant',
    "Chef's Table by Chef Stephan (Western Omakase, Fine Dining)": 'Western restaurant',
    "Chen's": 'Chinese restaurant',
    'Chengdu Bowl Tanjong Pagar 成都Bowl': 'Chinese restaurant',
    'Cherry & Oak': 'Fusion restaurant',
    'Wannian Stonepot Fish': 'Chinese restaurant',
    'Yuet Sing Seafood': 'Chinese restaurant',
    'Yi Zun Noodle @ Marina Square': 'Chinese restaurant',
    'Alijiang': 'Chinese restaurant',
    'Penang Culture': 'Malaysian restaurant',
    'Western Mahua': 'Western restaurant',
    'GLC Hao Yun Lai Restaurant (好运来餐厅）': 'Chinese restaurant',
    'Al Madinah Restaurant': 'Halal restaurant',
    'Overrice (Voted Best Halal Restaurant near Haji Lane)': 'Halal restaurant',
    'Selera Serambi by Tang Tea House': 'Halal restaurant',
    'Bumbu Restaurant': 'Indonesian restaurant',
    'Chuan Kee Seafood': 'Chinese restaurant',
    'Chuan Kee Seafood Toa Payoh': 'Chinese restaurant',
    'Colonial Club Signatures': 'Western restaurant',
    'Comida Mexicana Singapore': 'Mexican restaurant',
    'Crafted by Peter Zwiener': 'Western restaurant',
    'DaXi 大喜 - VivoCity': 'Chinese restaurant',
    'Dapur Penyet @ City Plaza': 'Indonesian restaurant',
    'JB Garden Seafood Restaurant': 'Chinese restaurant',
    'Din Tai Fung': 'Chinese restaurant',
    'Dum Pukht Grill & Curry': 'Indian restaurant',
    'Dungeon by IL Fiore': 'Italian restaurant',
    'Ristorante Vista Duomo': 'Italian restaurant',
    'El Mesa Filipino Seafood & Grill Clarke Quay': 'Filipino restaurant',
    'Element Restaurant Amara Singapore': 'International restaurant',
    'Ellenborough Market Café': 'Peranakan restaurant',
    'Empire Hotpot & Cantonese Cuisine': 'Chinese restaurant',
    'Estuary Seafood Restaurant Bar - Event Space Orchard Road': 'Seafood restaurant',
    'Cherki': 'Fusion restaurant',
    'Olive Vine Pasta Fusion': 'Fusion restaurant',
    'Tambi Restaurant': 'Indian restaurant',
    "Martin's Kitchen": 'Western restaurant',
    'Quay House': 'Western restaurant',
    'ilmiri Korean Fusion Cuisine': 'Korean restaurant',
    'LECOQ': 'French restaurant',
    '15 Stamford': 'Western restaurant',
    'BYD by DXD': 'Fusion restaurant',
    'Kubo Wood-fired Cuisine & Wine Bar': 'Filipino restaurant',
    'Synthesis 食拿酒稳: Modern Chinese Restaurant & Cocktail Bar (Suntec City)': 'Chinese restaurant',
    'RACINES': 'French restaurant',
    'Tash Tish Tosh @ 50K': 'Western restaurant',
    'JU95': 'Fusion restaurant',
    'Fairytail Bar - By The Halal Mixologist': 'Fusion restaurant',
    'Feng Sheng Kampong Chicken Rice & Steamboat (24 Hours) | 豐盛滑鸡火锅': 'Chinese restaurant',
    'Fish & Bones': 'Western restaurant',
    '#Foodcoholic': 'Fusion restaurant',
    'Frieda Beer Garden & German Restaurant': 'German restaurant',
    'Frog Meat Fish Head 美蛙魚頭自助火锅 和炒菜': 'Chinese restaurant',
    'Godmama at Parkway Parade - Modern Peranakan Restaurant Singapore': 'Peranakan restaurant',
    'Gold Ocean Curry Fish Head': 'Chinese restaurant',
    'Gong Yuan Ma La Tang': 'Chinese restaurant',
    'Gong Yuan Ma La Tang 宫源麻辣烫 @ 18 Tai Seng': 'Chinese restaurant',
    'Good Luck BBQ 上上签四川小酒馆': 'Chinese restaurant',
    'Great Nanyang Heritage Cafe 大南洋': 'Malaysian restaurant',
    'Guccio Ristorante @Telok Ayer': 'Italian restaurant',
    'Hahahotpot Jalan Pisang': 'Chinese restaurant',
    'Abang Dol': 'Indonesian restaurant',
    'Restoran Ke Ren Lai': 'Chinese restaurant',
    '109 Yong Tau Foo': 'Chinese restaurant',
    'Jason Niang Dou Fu': 'Chinese restaurant',
    'Orchard Yong Tau Fu': 'Chinese restaurant',
    'The Beef House': 'Chinese restaurant',
    'Gem Fresh Yong Tau Foo': 'Chinese restaurant',
    'Bagus LaMian': 'Chinese restaurant',
    'Thunderbolt Tea by Boon Lay Traditional Hakka Lui Cha': 'Chinese restaurant',
    'Hakka Yong Tau Foo': 'Chinese restaurant',
    'Hannibal Singapore - European Grill and Bar': 'European restaurant',
    'HarriAnns Nonya Table': 'Peranakan restaurant',
    'Genius Central Singapore': 'Café',
    'Hei Lun Shi Tang 黑轮食堂': 'Chinese restaurant',
    'Hong Fan Tian 红翻天 Mala Hotpot': 'Chinese restaurant',
    'Hopscotch (Capitol)': 'Fusion restaurant'
}

CATEGORY_TO_CUISINE = {
    'African': 'African',
    'American': 'American',
    'Andhra': 'Indian',
    'Argentinian': 'Latin American',
    'Art cafe': 'Cafe',
    'Asian': 'Asian',
    'Asian fusion': 'Fusion',
    'Australian': 'Australian',
    'Authentic Japanese': 'Japanese',
    'Bakso': 'Indonesian',
    'Bar': 'Bar',
    'Bar & grill': 'Bar',
    'Barbecue': 'Barbecue',
    'Basque': 'Spanish',
    'Biryani': 'Indian',
    'Bistro': 'Casual',
    'Brasserie': 'Casual',
    'Brazilian': 'Latin American',
    'Breakfast': 'Cafe',
    'Brunch': 'Cafe',
    'Buffet': 'Buffet',
    'Cafe': 'Cafe',
    'Café': 'Cafe',
    'Cantonese': 'Chinese',
    'Cat cafe': 'Cafe',
    'Catalonian': 'Spanish',
    'Cha chaan teng (Hong Kong-style cafe)': 'Chinese',
    'Chettinad': 'Indian',
    'Chicken': 'Casual',
    'Chinese': 'Chinese',
    'Chinese noodle': 'Chinese',
    'Cocktail bar': 'Bar',
    'Conveyor belt sushi': 'Japanese',
    'Crab house': 'Seafood',
    'Creperie': 'French',
    'Delivery Chinese': 'Chinese',
    'Dessert': 'Dessert',
    'Dim sum': 'Chinese',
    'Diner': 'American',
    'Dumpling': 'Chinese',
    'Eastern European': 'Eastern European',
    'European': 'European',
    'Family': 'Family',
    'Filipino': 'Asian',
    'Fine dining': 'Fine dining',
    'Fish and seafood': 'Seafood',
    'French': 'French',
    'French steakhouse': 'French',
    'Fried chicken takeaway': 'Casual',
    'Fusion': 'Fusion',
    'Gastropub': 'Casual',
    'German': 'German',
    'Gluten-free': 'Health food',
    'Greek': 'Mediterranean',
    'Grill': 'Barbecue',
    'Hakka': 'Chinese',
    'Halal': 'Halal',
    'Hamburger': 'Casual',
    'Health food': 'Health food',
    'Hong Kong style fast food': 'Chinese',
    'Hot pot': 'Chinese',
    'Hunan': 'Chinese',
    'Indian': 'Indian',
    'Indian Muslim Restaurant': 'Indian',
    'Indonesian': 'Indonesian',
    'International': 'International',
    'Israeli': 'Middle Eastern',
    'Italian': 'Italian',
    'Izakaya': 'Japanese',
    'Japanese': 'Japanese',
    'Japanese steakhouse': 'Japanese',
    'Japanized western': 'Fusion',
    'Kaiseki': 'Japanese',
    'Kebab Shop': 'Middle Eastern',
    'Korean': 'Korean',
    'Korean barbecue': 'Korean',
    'Kushiyaki': 'Japanese',
    'Latin American': 'Latin American',
    'Lebanese': 'Middle Eastern',
    'Local': 'Local',
    'Malaysian': 'Local',
    'Meat dish': 'Barbecue',
    'Mediterranean': 'Mediterranean',
    'Mexican': 'Mexican',
    'Middle Eastern': 'Middle Eastern',
    'Modern Australian': 'Australian',
    'Modern European': 'European',
    'Modern French': 'French',
    'Modern Indian': 'Indian',
    'Modern izakaya': 'Japanese',
    'Moroccan': 'Middle Eastern',
    'Nepalese': 'Asian',
    'Noodle shop': 'Asian',
    'North Eastern Indian': 'Indian',
    'North Indian': 'Indian',
    'Nyonya': 'Peranakan',
    'Okonomiyaki': 'Japanese',
    'Oyster bar': 'Seafood',
    'Padang': 'Indonesian',
    'Pakistani': 'Asian',
    'Pan-Asian': 'Asian',
    'Pasta shop': 'Italian',
    'Peranakan': 'Peranakan',
    'Persian': 'Middle Eastern',
    'Peruvian': 'Latin American',
    'Pizza': 'Italian',
    'Portuguese': 'Mediterranean',
    'Punjabi': 'Indian',
    'Ramen': 'Japanese',
    'Russian': 'Eastern European',
    'Satay': 'Local',
    'Seafood': 'Seafood',
    'Seafood donburi': 'Japanese',
    'Shabu-shabu': 'Japanese',
    'Sichuan': 'Chinese',
    'Singaporean': 'Local',
    'Soba noodle shop': 'Japanese',
    'Soup': 'Casual',
    'Soup shop': 'Casual',
    'Southeast Asian': 'Local',
    'Southern Italian': 'Italian',
    'Spanish': 'Spanish',
    'Sri Lankan': 'Asian',
    'Steak house': 'Western',
    'Steamboat': 'Asian',
    'Sukiyaki and Shabu Shabu': 'Japanese',
    'Sushi': 'Japanese',
    'Sweets and dessert buffet': 'Dessert',
    'Swiss': 'European',
    'Syokudo and Teishoku': 'Japanese',
    'Taco': 'Mexican',
    'Taiwanese': 'Asian',
    'Tapas': 'Spanish',
    'Tapas bar': 'Spanish',
    'Tempura': 'Japanese',
    'Tempura donburi': 'Japanese',
    'Teppanyaki': 'Japanese',
    'Tex-Mex': 'Mexican',
    'Thai': 'Thai',
    'Tonkatsu': 'Japanese',
    'Traditional': 'Family',
    'Turkish': 'Middle Eastern',
    'Unagi': 'Japanese',
    'Vegan': 'Health food',
    'Vegetarian': 'Health food',
    'Vegetarian cafe and deli': 'Health food',
    'Vietnamese': 'Asian',
    'Western': 'Western',
    'Wine bar': 'Bar',
    'Yakiniku': 'Japanese',
    'Yakitori': 'Japanese'
}

POSTAL_TO_DISTRICT = {
    '01': '01', '02': '01', '03': '01', '04': '01', '05': '01', '06': '01',
    '07': '02', '08': '02', '09': '04', '10': '04', '11': '05', '12': '05',
    '13': '05', '14': '03', '15': '03', '16': '03', '17': '06', '18': '07',
    '19': '07', '20': '08', '21': '08', '22': '09', '23': '09', '24': '10',
    '25': '10', '26': '10', '27': '10', '28': '11', '29': '11', '30': '11',
    '31': '12', '32': '12', '33': '12', '34': '13', '35': '13', '36': '13',
    '37': '13', '38': '14', '39': '14', '40': '14', '41': '14', '42': '15',
    '43': '15', '44': '15', '45': '15', '46': '16', '47': '16', '48': '16',
    '49': '17', '50': '17', '51': '18', '52': '18', '53': '19', '54': '19',
    '55': '19', '56': '20', '57': '20', '58': '21', '59': '21', '60': '22',
    '61': '22', '62': '22', '63': '22', '64': '22', '65': '23', '66': '23',
    '67': '23', '68': '23', '69': '24', '70': '24', '71': '24', '72': '25',
    '73': '25', '75': '27', '76': '27', '77': '26', '78': '26', '79': '28',
    '80': '28', '81': '17', '82': '19'
}

DISTRICT_TO_REGION = {
    '01': 'City', '02': 'City', '03': 'South', '04': 'South', '05': 'West', '06': 'City',
    '07': 'City', '08': 'Central', '09': 'Central', '10': 'Central', '11': 'Central', '12': 'Central',
    '13': 'East', '14': 'East', '15': 'East', '16': 'East', '17': 'East', '18': 'East',
    '19': 'North', '20': 'North', '21': 'West', '22': 'West', '23': 'West', '24': 'West',
    '25': 'North', '26': 'North', '27': 'North', '28': 'North'
}
################## VALIDATIONS #################
