import os

# mapbox
MAP_API = os.environ.get('MAP_API')

##################  VARIABLES  ##################



##################  CONSTANTS  #####################
# main_category to remove from restaurant_name.csv1
CATS_TO_REMOVE = ['ATM', 'Accountant', 'Acupuncture clinic', 'Advertising agency', 'After school program',
'Air conditioning store', 'Alcoholic beverage wholesaler', 'Anglican church', 'Antique store', 'Apartment building',
'Apartment complex', 'Art center', 'Art gallery', 'Art museum', 'Art studio', 'Artist', 'Artistic handicrafts',
'Association / Organization', 'Athletic field', 'Auditor', 'Açaí shop', 'Baby store', 'Bakery', 'Ballet school', 'Bank',
'Barber shop', 'Bazar', 'Beauty product supplier', 'Beauty salon', 'Bed & breakfast', 'Bicycle club', 'Book store',
'Boutique', 'Branding agency', 'Bridal shop', 'Bubble tea store', 'Bus Interchange', 'Bus depot', 'Bus stop', 'Business center',
'Business management consultant', 'Business to business service', 'Butcher shop', 'Cake shop', 'Camera store', 'Camping Ground',
'Candle store', 'Car dealer', 'Car detailing service', 'Car wash', 'Caterer', 'Catering food and drink supplier',
'Catholic church', 'Cement manufacturer', 'Charity', 'Chartered accountant', "Children's clothing store", 'Chinese Takeaway',
'Chinese language school', 'Cinema', 'Clothing store', 'Club', 'Coaching center', 'Coffee shop', 'Coffee store', 'Coffee wholesaler',
'Commercial cleaning service', 'Commercial real estate inspector', 'Community garden', 'Computer security service',
'Computer store', 'Computer support and services', 'Condominium complex', 'Confectionery store', 'Construction company',
'Consultant', 'Contractor', 'Convenience store', 'Corporate gift supplier', 'Corporate office', 'Cosmetics and perfumes supplier',
'Counselor', 'Coworking space', 'Credit counseling service', 'Cultural association', 'Curtain and upholstery cleaning service',
'Dance school', 'Dance store', 'Day care center', 'Day spa', 'Delivery Restaurant', 'Dental clinic', 'Department store',
'Design agency', 'Designer Clothing Shop', 'Diving center', 'E-commerce service', 'Education center', 'Educational institution',
'Educational testing service', 'Electronics manufacturer', 'Electroplating Service', 'Employment agency', 'Employment center',
'Employment consultant', 'Engineer', 'Event management company', 'Event planner', 'Event venue', 'Family service center',
'Fashion accessories store', 'Fast food restaurant', 'Finance broker', 'Financial consultant', 'Financial institution', 'Financial planner', 'Fish store',
'Florist', 'Flower delivery', 'Food court', 'Food manufacturer', 'Food producer', 'Food products supplier', 'Freight forwarding service',
'Frozen food store', 'Fruit wholesaler', 'Furniture store', 'Garden', 'Garden center', 'Gemologist', 'General practitioner',
'Gift shop', 'Gold dealer', 'Goldsmith', 'Gourmet grocery store', 'Government office', 'Grocery store', 'Gym and Fitness Centre',
'HDB Flats', 'Hair salon', 'Hairdresser', 'Hardware store', 'Hawker Stall', 'Hawker center', 'Health and beauty shop',
'Health food store', 'Health spa', 'Hematologist', 'Heritage building', 'Hiking area', 'Holding company', 'Homewares Store',
'Hostel', 'Hotel', 'House cleaning service', 'Housing development', 'Ice cream shop', 'Ice supplier', 'Importer',
'Importer and Exporter', 'Indian grocery store', 'Indoor golf course', 'Industrial Real Estate Agency', 'Industrial equipment supplier',
'Industry', 'Information services', 'Insurance', 'Insurance company', 'Interior designer', 'Internet marketing service',
'Italian grocery store', 'Japanese confectionery shop', 'Japanese grocery store', 'Jeweler', 'Jewelry store', 'Kiosk', 'Kitchen',
'Laboratory equipment supplier', 'Language school', 'Law firm', 'Lawyer', 'Learning center', 'Legal services', 'Light rail station',
'Lighting store', 'Live music venue', 'Local government office', 'Lodging', 'Lottery retailer', 'Luggage store', 'MRT/LRT Station',
'Makerspace', 'Manufacturer', 'Market', 'Marketing agency', 'Marketing consultant', 'Martial arts club', 'Massage spa', 'Maternity store',
'Mattress store', 'Media company', 'Medical Center', 'Medical clinic', 'Medical equipment supplier', 'Memorial estate', 'Memorial park',
'Mining company', 'Monument maker', 'Motorcycle rental agency', 'Movie rental store', 'Moving and storage service', 'Muay Thai boxing gym',
'Museum', 'Music management and promotion', 'Music producer', 'Music school', 'Nail salon', 'National forest',
'Non-governmental organization', 'Non-profit organization', 'Occupational therapist', 'Optician', 'Optometrist', 'Oral surgeon',
'Organic food store', 'Otolaryngologist', 'Park', 'Parking lot', 'Pastry shop', 'Patisserie', 'Performing arts group', 'Performing arts theater',
'Personal trainer', 'Pest control service', 'Pet Shop', 'Pharmacy', 'Photographer', 'Photography', 'Photography service',
'Plant nursery', 'Plastic products supplier', 'Playground', 'Police station', 'Preschool', 'Print shop', 'Property Investment',
'Property management company', 'Pub', 'Public parking space', 'Publisher', 'Real estate agency', 'Real estate agent',
'Real estate consultant', 'Real estate developer', 'Recording studio', 'Recruiter', 'Religious destination', 'Religious organization',
'Restaurant supply store', 'Scenic spot', 'School', 'Seafood wholesaler', 'Serviced accommodation', 'Shipping and mailing service',
'Shipping service', 'Shoe Shop', 'Shoe repair shop', 'Shop', 'Shopping mall', 'Social club', 'Software company', 'Souvenir store',
'Sports bar', 'Supermarket', 'Swimming school', 'Tailor', 'Takeaways', 'Taoist temple', 'Tattoo and piercing shop', 'Tattoo shop',
'Tea store', 'Tiffin center', 'Tourist attraction', 'Toy store', 'Trading company', 'Transport interchange', 'Transportation service',
'Travel agency', 'Tutoring service', 'Unknown', 'Used clothing store', 'Video production service', 'Walk-in clinic', 'Warehouse',
'Waxing hair removal service', 'Website designer', 'Wedding photographer', 'Wedding planner', 'Wedding store', 'Wedding venue',
'Wellness center', 'Wellness program', 'Wholesale food store', 'Wholesaler', 'Wine cellar', "Women's clothing store", 'Yoga studio',
'Youth Centre', 'Indoor playground', 'Food manufacturing supply', 'Kitchen supply store', 'Chocolate shop', 'Fruit and vegetable wholesaler',
'Chinese tea house', 'Wholesale bakery', 'Dessert shop', 'Coffee stand', 'Chinese bakery', 'Sushi takeaway', 'Coffee roasters', 'Karaoke bar',
'Food and drink', 'Steamed bun shop', 'Butcher shop deli', 'Tea and coffee shop', 'Stationery store', 'Chocolate artisan', 'Tea house',
'Pizza takeaway', 'Delivery Chinese', 'Self service restaurant', 'Sundae restaurant', 'Chocolate cafe', 'Deli', ''
'Farm shop', 'Lounge', 'Sandwich shop', 'Japanese sweets restaurant',
]

PLACE_ID_TO_DROP = [
    'ChIJh5Y59BQT2jERURiZLDQx4nw',
    'ChIJZ1fwClsb2jERObWFCMIH9vs',
    'ChIJPQnKqsAZ2jERwwkvvSyGZFg',
    'ChIJq6p6aIEa2jERLuWrj4ANh8E',
    'ChIJN33CKWIQ2jERMg_rME_Bay0',
    'ChIJd4WNfZ4Z2jERg12q-wfG2as',
    'ChIJ71CS0r0Z2jER8-smeu34jjY',
    'ChIJL4PDN6kZ2jERThaNWhOn098',
    'ChIJXd0PKYEX2jERYrueyc06grw',
    'ChIJ6Ykv9HEQ2jERsEXyHWa-R9Q',
    'ChIJVVUVem4Q2jERWIpWwfLUvOM',
    'ChIJ_aBCmBQZ2jERq5LkmNBX4ow',
    'ChIJAWnNhWgX2jERdqeKX3ll9_A',
    'ChIJ56hvaFoQ2jER6UYrXGNDQGc',
    'ChIJYzNuVSQX2jERq0kUBaonauY',
    'ChIJ-5iwVQsZ2jERDYQr5iyYDbI',
    'ChIJR-uLmRIZ2jERB3x-oYjX6-8',
    'ChIJu63tBLEZ2jER4BWy9m52vtI',
    'ChIJl0y967gZ2jER61Sh6YJd_Yg',
    'ChIJE3D9Nysa2jERVnXUtHpekrE',
    'ChIJzSendw0Z2jERTiGG5HBCUdI',
    'ChIJZVV0h2wZ2jER62ZOIpoV2P8',
    'ChIJ__8PEIka2jERVGgDfS-2K10',
    'ChIJS_BEA7oZ2jER2GK5z-e8qoQ',
    'ChIJAQAASX0Z2jERVYuMyQfqAQA',
    'ChIJx9FYtnUZ2jER922k1B_LAzk',
    'ChIJKf5YyxIZ2jERILku5keIlJg',
    'ChIJUcN6xW0Y2jERC2-GL6l2z7E',
    'ChIJaW3kmZYV2jER-uORG7aXKyU',
    'ChIJsQVGb_oX2jERvDAu0xkL6zA',
    'ChIJrTFZ9rcZ2jER2xBp6b8aOHA',
    'ChIJ7-afsQwZ2jER2f0eExqzue0',
    'ChIJezI5f7gX2jERa0J7b7iGbuk',
    'ChIJnxVgCG0Z2jER3-HA5RXp6Qw',
    'ChIJV_7XqfYX2jERCCwSnrmQ3Nc',
    'ChIJq6q278sb2jERWGHFlfEVmfY',
    'ChIJ8RANNaEZ2jERgf3U0gAdTgE',
    'ChIJZWEkZgsZ2jER0WnuE6HDzoE',
    'ChIJEUEayA4Z2jERNH_S8TPONm4',
    'ChIJ3eVZlQ4Z2jERX34jdgqlI28',
    'ChIJ-TsVF6kb2jER1_NGlLmqZmk',
    'ChIJvSxGnpcZ2jERJCmBscFz3Dw',
    'ChIJ3Tcl0IwZ2jER7_dBq_HSCbA',
    'ChIJKdihA68Z2jER07IZ_I3hEVI',
    'ChIJicht9G0Y2jER1DYdsrIIJw8',
    'ChIJ__8_wYwZ2jERtCSn02_fhzY',
    'ChIJo5fvvQwZ2jERz_JUcD4fzkg',
    'ChIJ__-vj-8Z2jERhye3e6pRpaM',
    'ChIJfaAGgMgZ2jERwVcV4SINwwg',
    'ChIJYd_hd0kZ2jERN9FWlI4xJto',
    'ChIJ9eNkeP4b2jERmH8pwHymE6M',
    'ChIJk0XVZ9YZ2jERuGEbtTayWNA',
    'ChIJ5z4oO2MZ2jERB3lOJkfCyhw',
    'ChIJa58Ty48T2jER7w4mWnrfWEM'
]

POSTAL_TO_DISTRICT = {
    '01': '01', '02': '01', '03': '01', '04': '01', '05': '01', '06': '01',
    '07': '02', '08': '02', '09': '04', '10': '04', '11': '05', '12': '05',
    '13': '05', '14': '03', '15': '03', '16': '03', '17': '06', '18': '07',
    '19': '07', '20': '08', '21': '08', '22': '09', '23': '09', '24': '10',
    '25': '10', '26': '10', '27': '10', '28': '11', '29': '11', '30': '11',
    '31': '12', '32': '12', '33': '12', '34': '13', '35': '13', '36': '13',
    '37': '13', '38': '14', '39': '14', '40': '14', '41': '14', '42': '15',
    '43': '15', '44': '15', '45': '15', '46': '16', '47': '16', '48': '16',
    '49': '17', '50': '17', '51': '18', '52': '18', '53': '19', '54': '19',
    '55': '19', '56': '20', '57': '20', '58': '21', '59': '21', '60': '22',
    '61': '22', '62': '22', '63': '22', '64': '22', '65': '23', '66': '23',
    '67': '23', '68': '23', '69': '24', '70': '24', '71': '24', '72': '25',
    '73': '25', '75': '27', '76': '27', '77': '26', '78': '26', '79': '28',
    '80': '28', '81': '17', '82': '19'
}

DISTRICT_TO_REGION = {
    '01': 'City', '02': 'City', '03': 'South', '04': 'South', '05': 'West', '06': 'City',
    '07': 'City', '08': 'Central', '09': 'Central', '10': 'Central', '11': 'Central', '12': 'Central',
    '13': 'East', '14': 'East', '15': 'East', '16': 'East', '17': 'East', '18': 'East',
    '19': 'North', '20': 'North', '21': 'West', '22': 'West', '23': 'West', '24': 'West',
    '25': 'North', '26': 'North', '27': 'North', '28': 'North'
}
################## VALIDATIONS #################
