import os

# mapbox
MAP_API = os.environ.get('MAP_API')

##################  VARIABLES  ##################



##################  CONSTANTS  #####################
# main_category to remove from restaurant_name.csv1
CATS_TO_REMOVE = ['Manufacturer', 'Maternity store', 'Mining company', 'Barber shop', 'Preschool', 'Bazar',
"Women's clothing store", 'Dessert shop', 'Art gallery', 'Branding agency', 'Medical equipment supplier',
'Waxing hair removal service', 'Day care center', 'Computer support and services', 'E-commerce service',
'Grocery store', 'Lawyer', 'Educational institution', 'Importer', 'Coffee shop', 'Public parking space',
'Food and drink', 'Medical Center', 'Day spa', 'Kitchen supply store', 'Karaoke bar', 'Delivery Chinese',
'Chinese language school', 'Credit counseling service', 'Artist', 'Goldsmith', 'MRT/LRT Station',
'Youth Centre', 'Education center', 'Walk-in clinic', 'Caterer', 'Tourist attraction', 'Design agency',
'Playground', 'Hiking area', 'Personal trainer', 'Muay Thai boxing gym', 'Non-profit organization',
'Optician', 'Transport interchange', 'Wellness center', 'Indoor playground', 'Japanese sweets restaurant',
'Plastic products supplier', 'Fish store', 'Dog cafe', 'Candle store', 'Shopping mall',
'Health and beauty shop', 'Clothing store', 'Association / Organization', 'Medical clinic',
'Food manufacturer', 'Pest control service', 'Souvenir store', 'Delivery Restaurant',
'Tattoo and piercing shop', 'Law firm', 'Contractor', 'Gold dealer', 'Cement manufacturer', 'Lounge',
'Oral surgeon', 'Property management company', 'Construction company', 'Website designer', 'Tattoo shop',
'Furniture store', 'Shop', 'Software company', 'Chinese bakery', 'Tea and coffee shop',
'Food manufacturing supply', 'Photographer', 'Print shop', 'Chinese Takeaway', 'Coffee roasters',
'Finance broker', 'Commercial cleaning service', 'Employment agency', 'Sports bar', 'Accountant',
'Organic food store', 'Industrial Real Estate Agency', 'Book store', 'Commercial real estate inspector',
'Self service restaurant', 'HDB Flats', 'Internet marketing service', 'Farm shop', 'Event planner', 'ATM',
'Government office', 'Açaí shop', 'Memorial park', 'Educational testing service', 'Photography',
'Computer security service', 'Food court', 'Financial institution', 'Homewares Store',
'Wedding photographer', 'Real estate consultant', 'Importer and Exporter', 'Art center', 'Media company',
'Pub', 'Hostel', 'Charity', 'Event venue', 'Computer store', 'Dance store', 'Fruit wholesaler',
'Chocolate cafe', 'Serviced accommodation', 'Social club', 'Designer Clothing Shop', 'Pet Shop',
'Police station', 'Hardware store', 'Pizza takeaway', 'Real estate developer', 'Counselor',
'Japanese confectionery shop', 'Curtain and upholstery cleaning service', 'Wine cellar', 'Tailor',
'Department store', 'Engineer', 'Bus Interchange', 'Interior designer', 'Housing development',
'Otolaryngologist', 'Shipping and mailing service', 'Food producer', 'General practitioner', 'Cake shop',
'Baby store', 'Financial planner', 'Gourmet grocery store', 'Performing arts theater', 'Massage spa',
'Occupational therapist', 'School', 'Bus depot', 'Language school', 'Mattress store', 'Shipping service',
'Live music venue', 'Jewelry store', 'Art studio', 'Catholic church', 'Sushi takeaway', 'Diving center',
'Sandwich shop', 'Indian grocery store', 'Chocolate shop', 'Wholesaler', 'Consultant',
'Local government office', 'Bus stop', 'Club', 'Tiffin center', 'Car detailing service',
'Indoor golf course', 'Ballet school', 'Jeweler', 'Artistic handicrafts', 'Art museum',
'Movie rental store', 'Condominium complex', 'Chinese tea house', 'Dental clinic', 'Wholesale food store',
'Chocolate artisan', 'Used clothing store', 'Corporate gift supplier', 'Seafood wholesaler',
'Legal services', 'Butcher shop', 'Employment center', 'Coffee store', 'Frozen food store',
'Hawker center', 'Business management consultant', 'After school program', 'Steamed bun shop', 'Deli',
'Ice cream shop', 'Plant nursery', 'Advertising agency', 'Bed & breakfast', 'Soup kitchen',
'Wedding venue', 'Health spa', 'Holding company', 'Catering food and drink supplier',
'Music management and promotion', 'Apartment building', 'Fruit and vegetable wholesaler',
'Real estate agent', 'Business to business service', 'Boutique', 'Wedding planner',
'Alcoholic beverage wholesaler', 'Cosmetics and perfumes supplier', 'Luggage store', 'Dance school',
'Lodging', 'Kitchen', 'Martial arts club', 'Florist', 'Lottery retailer', 'Toy store', 'Flower delivery',
'Music producer', 'Trading company', 'Beauty product supplier', 'Insurance company', 'Cinema',
'Optometrist', 'Heritage building', 'Bank', 'Tutoring service', 'Parking lot', 'Hairdresser',
'Makerspace', 'Publisher', 'Tea house', 'Butcher shop deli', 'Employment consultant', 'Stationery store',
'Coworking space', 'Marketing consultant', 'Performing arts group', 'Convenience store',
'Community garden', 'Business center', 'House cleaning service', 'Scenic spot', 'Health food store',
'Takeaways', 'Garden', 'Learning center', 'Monument maker', 'Wellness program', 'Bubble tea store',
'Bakery', 'Recording studio', 'Motorcycle rental agency', 'Garden center', 'Electronics manufacturer',
'Religious organization', 'Real estate agency', 'Cultural association', 'Shoe Shop',
'Family service center', 'Moving and storage service', 'Camping Ground', 'Chartered accountant',
'Financial consultant', 'Fashion accessories store', 'Confectionery store', 'Supermarket', 'Industry',
'Non-governmental organization', 'Rice restaurant', 'Religious destination', 'Haute French restaurant',
'Food products supplier', 'Memorial estate', 'Car dealer', 'Taoist temple', 'Japanese grocery store',
'National forest', 'Bridal shop', 'Event management company', 'Unknown', 'Pastry shop', 'Antique store',
'Nail salon', 'Museum', 'Light rail station', 'Beauty salon', 'Coaching center', 'Fast food restaurant',
'Video production service', 'Apartment complex', 'Tea store', 'Warehouse', 'Freight forwarding service',
'Photography service', 'Gym and Fitness Centre', 'Ice supplier', 'Coffee stand', 'Corporate office',
'Hawker Stall', 'Air conditioning store', 'Italian grocery store', 'Recruiter', 'Transportation service',
'Camera store', 'Laboratory equipment supplier', 'Travel agency', 'Music school', 'Auditor',
'Anglican church', 'Athletic field', 'Pharmacy', 'Shoe repair shop', 'Kiosk', 'Yoga studio',
'Restaurant supply store', 'Hair salon', 'Marketing agency', 'Swimming school', 'Wedding store',
'Hematologist', 'Gemologist', 'Property Investment', 'Coffee wholesaler', 'Wholesale bakery',
"Children's clothing store", 'Patisserie', 'Hotel', 'Lighting store', 'Gift shop', 'Bicycle club',
'Industrial equipment supplier', 'Information services', 'Salad shop', 'Car wash', 'Market',
'Electroplating Service', 'Sundae restaurant', 'Insurance', 'Acupuncture clinic', 'Park'
]

PLACE_ID_TO_DROP = [
    'ChIJh5Y59BQT2jERURiZLDQx4nw',
    'ChIJZ1fwClsb2jERObWFCMIH9vs',
    'ChIJPQnKqsAZ2jERwwkvvSyGZFg',
    'ChIJq6p6aIEa2jERLuWrj4ANh8E',
    'ChIJN33CKWIQ2jERMg_rME_Bay0',
    'ChIJd4WNfZ4Z2jERg12q-wfG2as',
    'ChIJ71CS0r0Z2jER8-smeu34jjY',
    'ChIJL4PDN6kZ2jERThaNWhOn098',
    'ChIJXd0PKYEX2jERYrueyc06grw',
    'ChIJ6Ykv9HEQ2jERsEXyHWa-R9Q',
    'ChIJVVUVem4Q2jERWIpWwfLUvOM',
    'ChIJ_aBCmBQZ2jERq5LkmNBX4ow',
    'ChIJAWnNhWgX2jERdqeKX3ll9_A',
    'ChIJ56hvaFoQ2jER6UYrXGNDQGc',
    'ChIJYzNuVSQX2jERq0kUBaonauY',
    'ChIJ-5iwVQsZ2jERDYQr5iyYDbI',
    'ChIJR-uLmRIZ2jERB3x-oYjX6-8',
    'ChIJu63tBLEZ2jER4BWy9m52vtI',
    'ChIJl0y967gZ2jER61Sh6YJd_Yg',
    'ChIJE3D9Nysa2jERVnXUtHpekrE',
    'ChIJzSendw0Z2jERTiGG5HBCUdI',
    'ChIJZVV0h2wZ2jER62ZOIpoV2P8',
    'ChIJ__8PEIka2jERVGgDfS-2K10',
    'ChIJS_BEA7oZ2jER2GK5z-e8qoQ',
    'ChIJAQAASX0Z2jERVYuMyQfqAQA',
    'ChIJx9FYtnUZ2jER922k1B_LAzk',
    'ChIJKf5YyxIZ2jERILku5keIlJg',
    'ChIJUcN6xW0Y2jERC2-GL6l2z7E',
    'ChIJaW3kmZYV2jER-uORG7aXKyU',
    'ChIJsQVGb_oX2jERvDAu0xkL6zA',
    'ChIJrTFZ9rcZ2jER2xBp6b8aOHA',
    'ChIJ7-afsQwZ2jER2f0eExqzue0',
    'ChIJezI5f7gX2jERa0J7b7iGbuk',
    'ChIJnxVgCG0Z2jER3-HA5RXp6Qw',
    'ChIJV_7XqfYX2jERCCwSnrmQ3Nc',
    'ChIJq6q278sb2jERWGHFlfEVmfY',
    'ChIJ8RANNaEZ2jERgf3U0gAdTgE',
    'ChIJZWEkZgsZ2jER0WnuE6HDzoE',
    'ChIJEUEayA4Z2jERNH_S8TPONm4',
    'ChIJ3eVZlQ4Z2jERX34jdgqlI28',
    'ChIJ-TsVF6kb2jER1_NGlLmqZmk',
    'ChIJvSxGnpcZ2jERJCmBscFz3Dw',
    'ChIJ3Tcl0IwZ2jER7_dBq_HSCbA',
    'ChIJKdihA68Z2jER07IZ_I3hEVI',
    'ChIJicht9G0Y2jER1DYdsrIIJw8',
    'ChIJ__8_wYwZ2jERtCSn02_fhzY',
    'ChIJo5fvvQwZ2jERz_JUcD4fzkg',
    'ChIJ__-vj-8Z2jERhye3e6pRpaM',
    'ChIJfaAGgMgZ2jERwVcV4SINwwg',
    'ChIJYd_hd0kZ2jERN9FWlI4xJto',
    'ChIJ9eNkeP4b2jERmH8pwHymE6M',
    'ChIJk0XVZ9YZ2jERuGEbtTayWNA',
    'ChIJ5z4oO2MZ2jERB3lOJkfCyhw',
    'ChIJa58Ty48T2jER7w4mWnrfWEM'
]

NAMES_TO_DROP = ['Leila katheera', 'Dempsey Hill', 'Encik Tan', 'Tian Huat Rice Stall',
'Mr Teh Tarik Eating House', 'Shake Shack (Suntec)', 'Shake Shack 89 Neil Road', 'Shake Shack Great World'
]

RESTAURANT_RECATEGORIZATION = {
'109 Yong Tau Foo': 'Chinese restaurant',
'15 Stamford': 'International restaurant',
'Absurdities Singapore': 'Experimental cuisine restaurant',
'Abundance: Taiwanese Restaurant & Craft Beer Bar (Redhill)': 'Taiwanese restaurant',
'Ah Lock & Co': 'Singaporean restaurant',
'Ajumma\'s Northpoint': 'Korean restaurant',
'Ajumma\'s Westgate': 'Korean restaurant',
'Alice Boulangerie & Restaurant': 'French bakery restaurant',
'Alijiang': 'Chinese restaurant',
'Anglo Indian Cafe & Bar': 'Indian restaurant',
'Arab Street Turkish & Western Restaurant': 'Turkish restaurant',
'Ashoka Tandoor Family Restaurant': 'Indian restaurant',
'Bacos': 'Western restaurant',
'Bagus LaMian': 'Chinese restaurant',
'Bearded Bella': 'Cafe',
'Bugis BBQ and Hotpot': 'Chinese BBQ and Hotpot restaurant',
'Caffe Fernet': 'Italian restaurant',
'Charlie\'s Restaurant & Bar (Boat Quay)': 'Western restaurant',
'Chef\'s Table by Chef Stephan (Western Omakase, Fine Dining)': 'Fine dining restaurant',
'Chen\'s': 'Chinese restaurant',
'Cherki': 'Peranakan restaurant',
'Cherry & Oak': 'Fusion restaurant',
'Chuan Kee Seafood': 'Chinese seafood restaurant',
'Comida Mexicana Singapore': 'Mexican restaurant',
'D\'Penyetz Jem': 'Indonesian restaurant',
'DaXi 大喜 - VivoCity': 'Chinese restaurant',
'Dum Pukht Grill & Curry': 'Indian restaurant',
'Eden Restaurant': 'International restaurant',
'Estuary Seafood Restaurant Bar - Event Space Orchard Road': 'Seafood restaurant',
'Fairytail Bar - By The Halal Mixologist': 'Bar',
'Feng Sheng Kampong Chicken Rice & Steamboat (24 Hours) | 豐盛滑鸡火锅': 'Chinese restaurant',
'Frieda Beer Garden & German Restaurant': 'German restaurant',
'GLC Hao Yun Lai Restaurant (好运来餐厅）': 'Chinese restaurant',
'Galangal': 'Thai restaurant',
'Genius Central Singapore': 'Healthy dining restaurant',
'Gold Ocean Curry Fish Head': 'Indian restaurant',
'Good Luck BBQ 上上签四川小酒馆': 'Chinese BBQ restaurant',
'Great Nanyang Heritage Cafe 大南洋': 'Singaporean restaurant',
'Hahahotpot Jalan Pisang': 'Hotpot restaurant',
'Hopscotch (Capitol)': 'Bar and restaurant',
'Huda Restaurant SG 胡大饭店': 'Chinese restaurant',
'Humpback': 'Seafood restaurant',
'JAAN By Kirk Westaway': 'French fine dining restaurant',
'Jason Niang Dou Fu': 'Chinese restaurant',
'Jia Xiang Sarawak Kuching Kolo Mee': 'Malaysian restaurant',
'Jiak Modern Tzechar @ Hillv2': 'Chinese restaurant',
'Josh\'s Grill': 'Western restaurant',
'Joséphine - French Cuisine & Wine Bar': 'French restaurant',
'Korat Thai Cafe': 'Thai restaurant',
'Kubo Wood-fired Cuisine & Wine Bar': 'Filipino restaurant',
'La Mensa Multi Cuisine': 'International restaurant',
'Lazy Lizard - Flora Vista': 'Western restaurant',
'Lepak at Sultan': 'Cafe',
'Lime Restaurant': 'International buffet restaurant',
'Lolla': 'Mediterranean restaurant',
'Làng Nướng 1980\'s - Authentic Vietnamese home-cooked Cuisine': 'Vietnamese restaurant',
'Madame Fan': 'Chinese restaurant',
'Makan@Jen': 'Buffet restaurant',
'Man Man Japanese Unagi (Clarke Quay)': 'Japanese restaurant',
'Meta Restaurant': 'Modern European restaurant',
'Nyonyas & Gentlemen Restaurant': 'Peranakan restaurant',
'ODETTE': 'French fine dining restaurant',
'Odette': 'French fine dining restaurant',
'Old Bibik\'s Peranakan Kitchen': 'Peranakan restaurant',
'Olive Vine Pasta Fusion': 'Italian fusion restaurant',
'Olivia Restaurant & Lounge': 'Spanish restaurant',
'Oscar\'s': 'Buffet restaurant',
'Overrice (Voted Best Halal Restaurant near Haji Lane)': 'Middle Eastern restaurant',
'Papa Ayam 313@somerset': 'Indonesian restaurant',
'Pastaria Abate': 'Italian restaurant',
'Penang Culture': 'Malaysian restaurant',
'Podi & Poriyal': 'Indian restaurant',
'Putra Minang Restaurant Bencoolen': 'Indonesian restaurant',
'Qi - House of Sichuan': 'Chinese restaurant',
'RACINES': 'French and Chinese restaurant',
'Ristorante Vista Duomo': 'Italian restaurant',
'SKAI Restaurant': 'Grill restaurant',
'San Laksa Steamboat Pte Ltd': 'Chinese restaurant',
'San Shu Gong Private Dining 三叔公私房菜': 'Chinese restaurant',
'Sanook Kitchen - City Square': 'Thai restaurant',
'Selera Serambi by Tang Tea House': 'Malay restaurant',
'Sibarita Habana': 'Spanish restaurant',
'Sibarita Restaurante': 'Spanish restaurant',
'Sinpopo Brand Restaurant @ TANGS': 'Singaporean restaurant',
'Siri House Dempsey': 'Contemporary restaurant',
'Sum Dim Sum (Bedok)': 'Chinese restaurant',
'Sum Dim Sum (Punggol)': 'Chinese restaurant',
'Summer Hill': 'French restaurant',
'Synthesis 食拿酒稳: Modern Chinese Restaurant & Cocktail Bar (Suntec City)': 'Chinese restaurant',
'TAP @ 9 Penang': 'Tapas restaurant',
'Tapas,24 Singapore': 'Spanish restaurant',
'The Beef House': 'Steakhouse',
'The Curry Wok (TCW)': 'Indian restaurant',
'The Dempsey Project': 'International restaurant',
'The French Ladle': 'French restaurant',
'The Guild': 'Bar',
'The Halia at Singapore Botanic Gardens': 'Modern European restaurant',
'The Mask Restaurant and Bar': 'Western restaurant',
'The Orchard Cafe': 'International buffet restaurant',
'Thevar': 'Indian fusion restaurant',
'Thien Long Vietnamese Food': 'Vietnamese restaurant',
'Tian Tian You Yu 天天友魚': 'Chinese seafood restaurant',
'Tiffin Room': 'Indian restaurant',
'Tilly\'s by Butcher Boy': 'Western restaurant',
'Ting Yuan Hotpot Buffet': 'Chinese hotpot restaurant',
'Tash Tish Tosh @ 50K': 'Halal restaurant',
'Town Restaurant': 'International buffet restaurant',
'True Cost': 'International restaurant',
'VENUE By Sebastian': 'Modern European restaurant',
'VIETSEA® I - VUA LẨU': 'Vietnamese hotpot restaurant',
'WAKUDA': 'Japanese restaurant',
'WINESTONE': 'Western restaurant',
'Waroeng Anak Indo': 'Indonesian restaurant',
'Wild Coco (Hamilton Road)': 'Fusion restaurant',
'Ya Ge - 雅阁 (Orchid Hotel SG)': 'Chinese restaurant',
'Yang Guo Fu Mala Tang 杨国福麻辣烫 @ Northpoint City': 'Chinese restaurant',
'YinJi Singapore': 'Chinese restaurant',
'Yì By Jereme Leung': 'Chinese fine dining restaurant',
'fennel by komala vilas': 'Indian restaurant',
'ilmiri Korean Fusion Cuisine': 'Korean restaurant',
'蜀都丰 SO DO FUN @ MIDTOWN HOUSE': 'Chinese restaurant',
'辣不辣 Labula BBQ Sichuan Restaurant @ Hougang Village': 'Chinese BBQ restaurant'
}

POSTAL_TO_DISTRICT = {
    '01': '01', '02': '01', '03': '01', '04': '01', '05': '01', '06': '01',
    '07': '02', '08': '02', '09': '04', '10': '04', '11': '05', '12': '05',
    '13': '05', '14': '03', '15': '03', '16': '03', '17': '06', '18': '07',
    '19': '07', '20': '08', '21': '08', '22': '09', '23': '09', '24': '10',
    '25': '10', '26': '10', '27': '10', '28': '11', '29': '11', '30': '11',
    '31': '12', '32': '12', '33': '12', '34': '13', '35': '13', '36': '13',
    '37': '13', '38': '14', '39': '14', '40': '14', '41': '14', '42': '15',
    '43': '15', '44': '15', '45': '15', '46': '16', '47': '16', '48': '16',
    '49': '17', '50': '17', '51': '18', '52': '18', '53': '19', '54': '19',
    '55': '19', '56': '20', '57': '20', '58': '21', '59': '21', '60': '22',
    '61': '22', '62': '22', '63': '22', '64': '22', '65': '23', '66': '23',
    '67': '23', '68': '23', '69': '24', '70': '24', '71': '24', '72': '25',
    '73': '25', '75': '27', '76': '27', '77': '26', '78': '26', '79': '28',
    '80': '28', '81': '17', '82': '19'
}

DISTRICT_TO_REGION = {
    '01': 'City', '02': 'City', '03': 'South', '04': 'South', '05': 'West', '06': 'City',
    '07': 'City', '08': 'Central', '09': 'Central', '10': 'Central', '11': 'Central', '12': 'Central',
    '13': 'East', '14': 'East', '15': 'East', '16': 'East', '17': 'East', '18': 'East',
    '19': 'North', '20': 'North', '21': 'West', '22': 'West', '23': 'West', '24': 'West',
    '25': 'North', '26': 'North', '27': 'North', '28': 'North'
}
################## VALIDATIONS #################
